version: '3.3'
services:
  webserver:
    environment:
      - VIRTUAL_HOST=zoomroulette.isitspringyet.be
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=zoomroulette.isitspringyet.be
      - LETSENCRYPT_EMAIL=marijnnn@gmail.com
    image: 'nginx:alpine'
    container_name: zoomroulette-webserver
    working_dir: /application
    volumes:
      - '.:/code'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './docker/certs:/etc/nginx/certs'
    depends_on:
      - php-fpm
    expose:
      - '80'
    ports:
      - '80:80'
      - '443:443'
  php-fpm:
    image: 'php:7.4-fpm-alpine'
    container_name: zoomroulette-php-fpm
    working_dir: /code
    expose:
      - '9000'
    volumes:
      - '.:/code'
    environment:
      - ZOOM_CLIENTID=${ZOOM_CLIENTID}
      - ZOOM_CLIENTSECRET=${ZOOM_CLIENTSECRET}
      - SLACK_CLIENTID=${SLACK_CLIENTID}
      - SLACK_CLIENTSECRET=${SLACK_CLIENTSECRET}
      - ROOT_URL=${ROOT_URL}
networks:
  default:
    external:
      name: marijnworks
