version: '3.3'
services:
  webserver:
    environment:
      - VIRTUAL_HOST=zoomroulette.isitspringyet.be
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=zoomroulette.isitspringyet.be
      - LETSENCRYPT_EMAIL=marijnnn@gmail.com
    image: 'nginx:alpine'
    container_name: zoomroulette-webserver
    working_dir: /application
    volumes:
      - '.:/code'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './docker/certs:/etc/nginx/certs'
    depends_on:
      - php-fpm
      - postgres
    expose:
      - '80'
    ports:
      - '80:80'
      - '443:443'
  php-fpm:
    build: ./docker/php
    container_name: zoomroulette-php-fpm
    working_dir: /code
    expose:
      - '9000'
    volumes:
      - '.:/code'
    environment:
      - ZOOM_CLIENTID=${ZOOM_CLIENTID}
      - ZOOM_CLIENTSECRET=${ZOOM_CLIENTSECRET}
      - SLACK_CLIENTID=${SLACK_CLIENTID}
      - SLACK_CLIENTSECRET=${SLACK_CLIENTSECRET}
      - SLACK_VERIFICATIONTOKEN=${SLACK_VERIFICATIONTOKEN}
      - SLACK_SIGNINGSECRET=${SLACK_SIGNINGSECRET}
      - ROOT_URL=${ROOT_URL}
      - DATABASE_URL=${DATABASE_URL}
  postgres:
    image: 'postgres:12-alpine'
    environment:
      - 'POSTGRES_USER:postgres'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    expose:
      - '5432'
    ports:
      - '5432:5432'
networks:
  default:
    external:
      name: marijnworks
