version: '3.3'
services:
  coffeeroulette-webserver:
    environment:
      - VIRTUAL_HOST=coffeeroulette.madewithlove.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=coffeeroulette.madewithlove.com
      - LETSENCRYPT_EMAIL=marijnnn@gmail.com
    image: 'nginx:alpine'
    container_name: coffeeroulette-webserver
    working_dir: /application
    volumes:
      - '.:/code'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './logs:/var/log/nginx'
    depends_on:
      - php-fpm
    expose:
      - '80'
  php-fpm:
    build: ./docker/php
    container_name: coffeeroulette-php-fpm
    working_dir: /code
    expose:
      - '9000'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - '.:/code'
    environment:
      - ZOOM_CLIENTID=${ZOOM_CLIENTID}
      - ZOOM_CLIENTSECRET=${ZOOM_CLIENTSECRET}
      - ZOOM_VERIFICATIONTOKEN=${ZOOM_VERIFICATIONTOKEN}
      - ROOT_URL=${ROOT_URL}
      - SLACK_CLIENTID=${SLACK_CLIENTID}
      - SLACK_CLIENTSECRET=${SLACK_CLIENTSECRET}
      - SLACK_SIGNINGSECRET=${SLACK_SIGNINGSECRET}
      - SLACK_VERIFICATIONTOKEN=${SLACK_VERIFICATIONTOKEN}
      - DISPLAY_ERROR_DETAILS=${DISPLAY_ERROR_DETAILS}
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - CRYPTO_SECRET=${CRYPTO_SECRET}
networks:
  default:
    external:
      name: marijnworks
